In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import statsmodels as stats
from scipy import stats
import pandas as pd
import os
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from xgboost import XGBRegressor
from xgboost import plot_importance
import sklearn
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer

import statsmodels as stats
from scipy import stats
import pandas as pd
import os

from sklearn.model_selection import train_test_split
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
# y = Y_OBP
import numpy as np
import re 
import matplotlib.pyplot as plt
import statsmodels as stats
from scipy import stats
import pandas as pd
import os
import numpy as np
import re 
import matplotlib.pyplot as plt
from sklearn.svm import SVR
import sklearn
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor, plot_importance
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from itertools import combinations
from tqdm import tqdm
from sklearn.metrics import mean_squared_error 
from sklearn.linear_model import LinearRegression

from sklearn.linear_model import RANSACRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, mean_squared_error

from lightgbm import LGBMRegressor, plot_importance
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import re
from sklearn.svm import SVR

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/빅콘테스트/data/PA70이상.csv',encoding='utf-8',index_col=0)

In [171]:
df_train

PCODE  GYEAR  GAMENUM  T_ID  ...     OBP_3     SLG_3     OPS_3     Y_SLG
0    60100   2018     70.0   0.0  ...  0.346154  0.464789  0.810943  0.533333
1    60558   2018    128.0   2.0  ...  0.333333  0.417910  0.751244  0.318182
2    60558   2019    123.0   2.0  ...  0.244898  0.276596  0.521494  0.416667
3    61102   2018    132.0   3.0  ...  0.342466  0.439394  0.781860  0.494382
4    61102   2019    132.0   3.0  ...  0.306122  0.409091  0.715213  0.543860
..     ...    ...      ...   ...  ...       ...       ...       ...       ...
214  69901   2019     55.0   5.0  ...  0.270000  0.344444  0.614444  0.507246
215  65898   2020     73.0   9.0  ...  0.285714  0.583333  0.869048  0.436364
216  50165   2020    117.0   3.0  ...  0.356322  0.445946  0.802268  0.545455
217  50506   2020    144.0   4.0  ...  0.378947  0.418605  0.797552  0.329193
218  50923   2020    136.0   5.0  ...  0.395604  0.719512  1.115117  0.514124

[219 rows x 68 columns]

In [ ]:
df_train = df_train[df_train['Y_SLG']>=0.3]
df_train = df_train.drop('Y_OBP',axis=1)
df_train

PCODE  GYEAR  GAMENUM  T_ID  ...     OBP_3     SLG_3     OPS_3     Y_SLG
0    60100   2018     70.0   0.0  ...  0.346154  0.464789  0.810943  0.533333
4    60558   2018    128.0   2.0  ...  0.333333  0.417910  0.751244  0.318182
5    60558   2019    123.0   2.0  ...  0.244898  0.276596  0.521494  0.416667
10   61102   2018    132.0   3.0  ...  0.342466  0.439394  0.781860  0.494382
11   61102   2019    132.0   3.0  ...  0.306122  0.409091  0.715213  0.543860
..     ...    ...      ...   ...  ...       ...       ...       ...       ...
507  69901   2019     55.0   5.0  ...  0.270000  0.344444  0.614444  0.507246
516  65898   2020     73.0   9.0  ...  0.285714  0.583333  0.869048  0.436364
521  50165   2020    117.0   3.0  ...  0.356322  0.445946  0.802268  0.545455
524  50506   2020    144.0   4.0  ...  0.378947  0.418605  0.797552  0.329193
526  50923   2020    136.0   5.0  ...  0.395604  0.719512  1.115117  0.514124

[219 rows x 68 columns]

In [ ]:
df_train.reset_index(drop=True, inplace=True)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/빅콘테스트/data/2021_x_test.csv',encoding='utf-8')

In [ ]:
df

PCODE  GYEAR  GAMENUM  T_ID  ...  BARREL_SUM_3     OBP_3     SLG_3     OPS_3
0  67341   2021     79.0   9.0  ...            12  0.410256  0.510204  0.920460
1  67872   2021     78.0   7.0  ...             8  0.324074  0.488889  0.812963
2  68050   2021     75.0   2.0  ...            15  0.505155  0.558442  1.063596
3  75847   2021     74.0   7.0  ...            15  0.427184  0.638554  1.065739
4  76232   2021     73.0   5.0  ...            19  0.455446  0.717647  1.173093
5  76290   2021     73.0   3.0  ...            17  0.367347  0.465116  0.832463
6  78224   2021     68.0   6.0  ...            12  0.351648  0.383562  0.735210
7  78513   2021     77.0   4.0  ...            16  0.417391  0.479592  0.896983
8  79192   2021     61.0   3.0  ...            19  0.438776  0.600000  1.038776
9  79215   2021     59.0   6.0  ...             3  0.388889  0.416667  0.805556

[10 rows x 67 columns]

In [ ]:
X_train = df_train.drop('Y_SLG',axis=1)
y_train = df_train['Y_SLG']
X_test = df

In [ ]:
from sklearn.model_selection import KFold, StratifiedKFold

def get_stacking_data(model, X_train, y_train, X_test, n_folds=5):
    kfold = KFold(n_splits = n_folds, shuffle=True)
    
    # 최종 모델에서 사용할 데이터 셋 셋팅(0 값으로)
    # 만약 shape가 (100, 10) 이었으면 폴드의 검증 과정에서 저장할 데이터는 (100, 1) 모양을 갖게 한다.
    train_fold_predict = np.zeros((X_train.shape[0], 1))
    # test는 X_test 값을 이용해서 매 폴드마다 예측을 하기 때문에 (100, fold개수) 만큼의 shape를 갖게 된다.
    # 그래서 해당 폴드마다 X_test의 예측 값을 해당 fold에 해당되는 열에 넣는다.
    test_predict = np.zeros((X_test.shape[0], n_folds))
    print("model : ", model.__class__.__name__)
    
    for cnt, (train_index, valid_index) in enumerate(kfold.split(X_train)):
        X_train_ = X_train.iloc[train_index]
        y_train_ = y_train.iloc[train_index]
        X_validation = X_train.iloc[valid_index]
        
        #학습
        model.fit(X_train_, y_train_)
        
        #해당 폴드에서 학습된 모델에다가 검증 데이터(X_validation)로 예측 후 저장
        train_fold_predict[valid_index, :] = model.predict(X_validation).reshape(-1, 1)
        
        #해당 폴드에서 생성된 모델에게 원본 테스트 데이터(X_test)를 이용해서 예측을 수행하고 저장
        test_predict[:, cnt] = model.predict(X_test)
    
    #for문이 끝나면 test_pred는 평균을 내서 하나로 합친다.
    test_predict_mean = np.mean(test_predict, axis =1).reshape(-1, 1)
    
    return train_fold_predict, test_predict_mean

In [ ]:
model1 = Lasso(alpha=1000) # 0.05
model2 = Ridge(alpha=500000) # 10000
model3 = ElasticNet(alpha= 100000, l1_ratio=0.01)
model4 = LGBMRegressor(lambda_l1= 0, lamda_l2=0, learning_rate=0.1, max_depth=-1, n_estimaotrs= 5000, num_leaves= 7)

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)

model :  Lasso
model :  Ridge
model :  ElasticNet


In [ ]:
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)

In [ ]:
print("원본 : ", X_train.shape, X_test.shape)
print("새로운 : ", new_X_train.shape, new_X_test.shape)

원본 :  (157, 67) (10, 67)
새로운 :  (157, 3) (10, 3)


In [ ]:
model4.fit(new_X_train, y_train)
stack_pred = model4.predict(new_X_test)

In [ ]:
stack_pred

array([0.33319093, 0.47938009, 0.34838976, 0.48908435, 0.54155456,
       0.49646934, 0.53185804, 0.42049458, 0.45576647, 0.42932701])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred2 = model4.predict(new_X_test)
print(stack_pred2)
print(stack_pred2.mean())

model :  Lasso
model :  Ridge
model :  ElasticNet
[0.44003373 0.4953823  0.40906047 0.46485775 0.46028406 0.51937261
 0.52304757 0.51115747 0.46841911 0.47556797]
0.47671830395413173


In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred3 = model4.predict(new_X_test)
print(stack_pred3.mean())
stack_pred3

model :  Lasso
model :  Ridge
model :  ElasticNet
0.45283843346400215


array([0.42251744, 0.48751107, 0.42222752, 0.39979285, 0.58511698,
       0.39206134, 0.4164477 , 0.46066608, 0.45453307, 0.4875103 ])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred4 = model4.predict(new_X_test)
print(stack_pred4.mean())
stack_pred4

model :  Lasso
model :  Ridge
model :  ElasticNet
0.48236865284246805


array([0.45362464, 0.49840529, 0.38453059, 0.52157908, 0.47916378,
       0.54219527, 0.54053415, 0.50723085, 0.40341777, 0.4930051 ])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred5 = model4.predict(new_X_test)
print(stack_pred5.mean())
stack_pred5

model :  Lasso
model :  Ridge
model :  ElasticNet
0.4582921428237004


array([0.44874958, 0.49469372, 0.43058346, 0.50695776, 0.43849803,
       0.48180671, 0.41428616, 0.46647394, 0.46070981, 0.44016226])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred6 = model4.predict(new_X_test)
print(stack_pred6.mean())
stack_pred6

model :  Lasso
model :  Ridge
model :  ElasticNet
0.42127320295985626


array([0.39089729, 0.48870592, 0.36704413, 0.43673307, 0.48400545,
       0.42214788, 0.44920837, 0.41327009, 0.39838815, 0.36233168])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred7 = model4.predict(new_X_test)
print(stack_pred7.mean())
stack_pred7

model :  Lasso
model :  Ridge
model :  ElasticNet
0.4590304015215441


array([0.39699026, 0.48770648, 0.37016834, 0.47395486, 0.4788417 ,
       0.45930792, 0.47904438, 0.49177525, 0.46275418, 0.48976065])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred8 = model4.predict(new_X_test)
print(stack_pred8.mean())
stack_pred8

model :  Lasso
model :  Ridge
model :  ElasticNet
0.47106335008653755


array([0.43033228, 0.48397098, 0.47366946, 0.45163078, 0.43124559,
       0.54262932, 0.4527758 , 0.4364263 , 0.49173047, 0.51622253])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred9 = model4.predict(new_X_test)
print(stack_pred9.mean())
stack_pred9

model :  Lasso
model :  Ridge
model :  ElasticNet
0.49594521920039414


array([0.51848878, 0.48318901, 0.51846375, 0.48161938, 0.55185893,
       0.41706784, 0.49283725, 0.51596264, 0.46966269, 0.51030192])

In [ ]:
model1_train, model1_test = get_stacking_data(model1, X_train, y_train, X_test)
model2_train, model2_test = get_stacking_data(model2, X_train, y_train, X_test)
model3_train, model3_test = get_stacking_data(model3, X_train, y_train, X_test)
new_X_train = np.concatenate((model1_train, model2_train, model3_train), axis = 1)
new_X_test = np.concatenate((model1_test, model2_test,model3_test), axis = 1)
model4.fit(new_X_train, y_train)
stack_pred10 = model4.predict(new_X_test)
print(stack_pred10.mean())
stack_pred10

model :  Lasso
model :  Ridge
model :  ElasticNet
0.4688408532437286


array([0.46113573, 0.48587023, 0.41195304, 0.51082934, 0.51481856,
       0.49924522, 0.46046575, 0.44449009, 0.47241208, 0.42718851])